name: 'devil-deployer-companion-action'
description: 'devil-deployer-companion-action'
author: 'cvgore'

inputs:
  appName:
    description: 'appName'
    required: true
  secretKey:
    description: 'secretKey'
    required: true
  url:
    description: 'url'
    required: true

runs:
  using: node20
  main: dist/index.js
